services:
  lisalikes-backend:
    build: ./backend
    container_name: spotify_curator_backend
    restart: unless-stopped
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_SECRET=${ADMIN_SECRET}
      - ADMIN_PATH=${ADMIN_PATH}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REDIRECT_URI=${SPOTIFY_REDIRECT_URI}
      - APP_DOMAIN=${APP_DOMAIN}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"

  lisalikes-frontend:
    build: ./frontend
    container_name: spotify_curator_frontend
    restart: unless-stopped
    depends_on:
      - lisalikes-backend
    ports:
      - "8080:80"
